### ISSUE TITLE
Hide some of the built-in commands

### ISSUE THREAD

**Issue by luchoster** [nitin42/terminal-in-react#18]
can we choose to hide some commands that we wouldn't use in the terminal?
For example, I don't want to show 'echo' or 'edit-line'. Can we pass the prop as false, in case we don't want certain commands?

**Comment by jcgertig** [comment]
#16 will allow you to pass in false into the descriptions for the command you don't want to show in the help output. It should be merged soon

**Comment by nitin42** [comment]
Oh great! @jcgertig thanks 😃

**Comment by jcgertig** [comment]
@luchoster this has been merged and will be out in the next release

**Comment by luchoster** [comment]
@jcgertig awesome, thanks so much!!!
I was going to ask if you guys released it to npm yet :) 
Again, thank you. I'll share my project later today with you guys

**Comment by luchoster** [comment]
hey @jcgertig @nitin42, any ETA for release the 2.1.1 to npm?
I'm having issues building my project :(

Thank you guys!

**Comment by nitin42** [comment]
Fixed. Published `2.2.1`! Should work now 👍

**Comment by luchoster** [comment]
you guys are awesome, thanks!!!

**Comment by nitin42** [comment]
@luchoster let me know if minimise, maximise and close are working!

**Comment by luchoster** [comment]
@nitin42 buttons work flawlessly. 
I'm still having issues with building and UglifyJS :(

```
Creating an optimized production build...
Failed to compile.

static/js/main.eed737f4.js from UglifyJs
Unexpected token: name (isLastCharLower) [./~/camelcase/index.js:4,0][static/js/main.eed737f4.js:27223,5]

error Command failed with exit code 1.
```

**Comment by nitin42** [comment]
Working on it!

**Comment by luchoster** [comment]
not sure if I'm being dumb but if I do this:
```
description={{
            echo: false,
            someCommand: 'blah blah blah',
            show: 'shows the instructions message',
            help: 'list all the available commands'
          }}
```
I get, `echo - false`, in the terminal screen.
Am I doing it completely wrong? lol

**Comment by nitin42** [comment]
Description describes all of your commands. Set echo to "Prints the input" !

**Comment by luchoster** [comment]
Oh I guess I didn't explain. 
I'm trying to hide echo from the list of commands.
#16 was supposed to have that option, to pass false to the description, to hide it from the help list

**Comment by nitin42** [comment]
Ok let me check!

**Comment by nitin42** [comment]
@jcgertig any idea ? What's the mechanism for mapping the bool ?

**Comment by nitin42** [comment]
#23 has changed some internals. I've fixed some (window max, min and close, getters and other fixes) but still, when we set `echo: false` nothing happens! 🤔

**Comment by nitin42** [comment]
@luchoster The build error is due to `camelcase` package. I've fixed this but waiting for @jcgertig for some changes.

**Comment by luchoster** [comment]
@nitin42 awesome. 
You guys are great.
I want to help you out, but I need to get more familiar with the internals of the component.

**Comment by nitin42** [comment]
@luchoster I've published `3.0.0-beta.0`. It should not give any build errors!

**Comment by luchoster** [comment]
to npm?
I'll check in a second, thanks!!!

**Comment by nitin42** [comment]
Yup

**Comment by luchoster** [comment]
ok, cool. I'll wait a few mins, still shows 'published 3hrs ago. 2.2.1'

**Comment by nitin42** [comment]
Use tag beta, `npm install terminal-in-react@3.0.0-beta.0`

**Comment by nitin42** [comment]
and let me know if there are any build error after installing !

**Comment by luchoster** [comment]
it's giving me errors still.
I also created a new project with just that has 'react', 'react-dom' and 'terminal' installed, to make sure it wasn't my current project, but same thing:

```
$ react-scripts build 
Creating an optimized production build...
Failed to compile.

static/js/main.07d5fae9.js from UglifyJs
Unexpected token: name (isLastCharLower) [./~/camelcase/index.js:4,0][static/js/main.07d5fae9.js:12218,5]

error Command failed with exit code 1.
```

**Comment by nitin42** [comment]
Try `3.0.0-beta1` now!

**Comment by nitin42** [comment]
3.0.0-beta2 is working!! 👍

**Comment by luchoster** [comment]
Yessss!!!
Also, the `description` has change now, to `descriptions` so maybe you should update the README.
Passing `echo: false` in the descriptions prop, it hides the command, but for some reason it doesn't do it for `edit-line`, not sure what's up with that one. 

Everything else is working fine

**Comment by nitin42** [comment]
Well, its beta and we haven't released V3 officially. I'm testing everything so .... its recommended to use `2.2.1` which is current stable release!

**Comment by luchoster** [comment]
yeah, I understand, just letting you know.

One more before I go to bed lol
After building the project, I get this error in my local prod version:

<img width="1919" alt="screen shot 2017-07-10 at 01 16 13" src="https://user-images.githubusercontent.com/694367/28008715-8824e274-650d-11e7-9132-49d6afa55aa6.png">

**Comment by nitin42** [comment]
Oh! This is related to `libraryTarget` (`umd`). Don't worry this will be fixed !

**Comment by luchoster** [comment]
Thanks @nitin42 I appreciate it!

**Comment by nitin42** [comment]
Interesting! 

With `babili-webpack-plugin`, there are no errors when building but with `UglifyJs` there are some strange errors regarding the syntax. I've checked everything related to the syntax and there is nothing wrong. @jcgertig any idea ?

**Comment by nitin42** [comment]
@luchoster seems like you are using `create-react-app` which uses UglifyJs for minifying. May be that's why you are getting these strange errors.

**Comment by nitin42** [comment]
![](https://i.gyazo.com/4f7c5659c5a1f87e9ab560ae49f5c6b8.png)

**Comment by jcgertig** [comment]
Yeah we don't currently have a good .babelrc we might want to move to something like

 ```javascript
{
  "presets": ["es2015", "react", "stage-1"],
  "plugins": [
    "transform-decorators-legacy",
    ["transform-es2015-modules-umd", {
      "globals": {
        "react": "React"
      }
    }]
  ]
}
```

**Comment by nitin42** [comment]
Btwn V3 released !!

**Comment by nitin42** [comment]
> Yeah we don't currently have a good .babelrc we might want to move to something like

@jcgertig are you working on this then ?

**Comment by luchoster** [comment]
@nitin42 yeah it kinda seemed to be an issue related to create-react-app.
I'll try to start a new project with my own boilerplate, hopefully that'll fix the building issue.

**Comment by nitin42** [comment]
Btw checkout the new release 🔥  @luchoster

**Comment by luchoster** [comment]
I already have, 3.0, right?
this is sweeeeeet!

**Comment by luchoster** [comment]
Just a quick follow up.
I ejected from `create-react-app` and removed the `new webpack.optimize.UglifyJsPlugin`.
Installed `babili-webpack-plugin` and included it without any options.
Project built with no issues!!!

**Comment by nitin42** [comment]
Yup. Its due to `UglifyJs` only!

**Comment by nitin42** [comment]
What did you build ? Btwn!

**Comment by luchoster** [comment]
yup.
Thanks again for all the help. I will fork this and hopefully help you guys out.
By the way, I have a live example: [http://checkitout.io/](url)

**Comment by nitin42** [comment]
Thanks! And 👉   `http://checkitout.io` is awesome 😃

**Comment by nitin42** [comment]
@jcgertig anything on `echo` option btwn ? It still shows when set to `false`

**Comment by luchoster** [comment]
@jcgertig @nitin42 actually no, the built-in commands props, are working fine. 
If you see on my site, it doesn't show, `echo` or `edit-line`.

**Comment by nitin42** [comment]
Checked again and its working 😅 . I was using an old example!

**Comment by jcgertig** [comment]
Gonna close this issue 😄
